#!/usr/bin/env python3
"""Export public crypto data to the site and D1 seed file.

Regenerates, from the single source of truth:
- resources/llm-catalog.json          (LLM/agent discovery manifest, PF-014)
- ahrondarnell-site/src/data/donations.ts  (public donation addresses)
- ahrondarnell-site/src/data/resources.ts  (catalog for the site resources page)
- workers/d1-seed.sql                 (INSERTs for donation_addresses + resources)

Public data only. Seeds/keys never leave state/crypto/. Idempotent.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from substrate.crypto import ResourceInventory, WalletManager

SITE = ROOT / "ahrondarnell-site"


def _ts_quote(value: str) -> str:
    return json.dumps(value)


def _write_donations_ts(manager: WalletManager) -> Path:
    wallets = manager.list_wallets()
    networks: dict[str, dict] = {}
    for wallet in wallets:
        if wallet.get("purpose") not in {"donations", "payments"}:
            continue
        network = str(wallet.get("network") or "polygon")
        address = wallet.get("addresses") or [""]
        if not address[0]:
            continue
        networks.setdefault(network, {"network": network, "tokens": []})
        networks[network]["tokens"].append({"symbol": "USDC", "address": address[0]})

    ts = "\n".join(
        [
            "// Generated by scripts/crypto/export_site_data.py — do not edit by hand.",
            "// Public addresses only; derived from state/crypto/wallets.json.",
            "",
            "export interface DonationNetwork {",
            "  network: string;",
            "  tokens: { symbol: string; address: string }[];",
            "}",
            "",
            "export const DONATIONS: DonationNetwork[] = "
            + json.dumps(list(networks.values()), indent=2)
            + ";",
            "",
        ]
    )
    path = SITE / "src" / "data" / "donations.ts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ts, encoding="utf-8")
    return path


def _write_resources_ts(inventory: ResourceInventory) -> Path:
    resources = [
        {
            "id": entry.get("id"),
            "title": entry.get("title"),
            "category": entry.get("category"),
            "description": entry.get("description", ""),
            "price_usdc": entry.get("price_usdc"),
            "free": bool(entry.get("free") or float(entry.get("price_usdc") or 0) == 0),
            "version": entry.get("version", "1.0"),
        }
        for entry in sorted(inventory.load(), key=lambda e: (e.get("category"), e.get("id")))
    ]
    ts = "\n".join(
        [
            "// Generated by scripts/crypto/export_site_data.py — do not edit by hand.",
            "// Mirror of resources/catalog.json (PF-014).",
            "",
            "export interface CatalogResource {",
            "  id: string;",
            "  title: string;",
            "  category: string;",
            "  description: string;",
            "  price_usdc: number;",
            "  free: boolean;",
            "  version: string;",
            "}",
            "",
            "export const CATALOG: CatalogResource[] = "
            + json.dumps(resources, indent=2)
            + ";",
            "",
        ]
    )
    path = SITE / "src" / "data" / "resources.ts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ts, encoding="utf-8")
    return path


def _write_d1_seed(inventory: ResourceInventory) -> Path:
    lines = [
        "-- Generated by scripts/crypto/export_site_data.py — do not edit by hand.",
        "-- Apply with: wrangler d1 execute crypto-payments --file workers/d1-seed.sql",
        "-- Upsert donation addresses (public only).",
        "",
    ]
    wallets = WalletManager(ROOT).list_wallets()
    for wallet in wallets:
        network = str(wallet.get("network") or "polygon")
        addresses = wallet.get("addresses") or []
        if not addresses:
            continue
        lines.append(
            f"INSERT INTO donation_addresses (network, token, address) VALUES "
            f"('{network}', 'USDC', '{addresses[0]}') "
            f"ON CONFLICT(network, token) DO UPDATE SET address = excluded.address;"
        )
    lines.append("")
    lines.append("-- Upsert catalog resources.")
    lines.append("")
    for entry in inventory.load():
        resource_id = str(entry.get("id") or "")
        title = str(entry.get("title") or "").replace("'", "''")
        category = str(entry.get("category") or "")
        price = float(entry.get("price_usdc") or 0)
        file_path = str(entry.get("file_path") or "")
        checksum = str(entry.get("checksum") or "")
        version = str(entry.get("version") or "1.0")
        free = 1 if price == 0 else 0
        lines.append(
            f"INSERT INTO resources (id, title, category, price_usdc, resource_path, checksum, version, free) VALUES "
            f"('{resource_id}', '{title}', '{category}', {price}, '{file_path}', "
            f"'{checksum}', '{version}', {free}) "
            f"ON CONFLICT(id) DO UPDATE SET title = excluded.title, category = excluded.category, "
            f"price_usdc = excluded.price_usdc, resource_path = excluded.resource_path, "
            f"checksum = excluded.checksum, version = excluded.version, free = excluded.free;"
        )
    path = ROOT / "workers" / "d1-seed.sql"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> int:
    manager = WalletManager(ROOT)
    inventory = ResourceInventory(ROOT)

    llm_path = ROOT / "resources" / "llm-catalog.json"
    llm_path.write_text(
        json.dumps(inventory.export_llm_catalog(), indent=2) + "\n", encoding="utf-8"
    )

    donations_path = _write_donations_ts(manager)
    resources_path = _write_resources_ts(inventory)
    d1_path = _write_d1_seed(inventory)

    print(json.dumps(
        {
            "llm_catalog": str(llm_path.relative_to(ROOT)),
            "donations": str(donations_path.relative_to(ROOT)),
            "resources": str(resources_path.relative_to(ROOT)),
            "d1_seed": str(d1_path.relative_to(ROOT)),
        },
        indent=2,
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
