"""Automated agent system for research, development, and moderation.

This package implements a roster of autonomous agents that run on a schedule
to perform research, development, and moderation tasks across repositories.
"""

from .core import (
    AGENT_ROLES,
    ALLOWED_AGENT_PROVIDERS,
    BRANCH_MAX_AGE_DAYS,
    CADENCE_SECONDS,
    TIER_AUTO,
    TIER_AUTO_IF_GREEN,
    TIER_HUMAN,
    VALID_CADENCES,
    AgentConfig,
    AgentConfigError,
    AgentRunResult,
    AgentStateStore,
    agent_branch_name,
    agent_status_payload,
    agents_file_path,
    bounded_validation_limits,
    cadence_bucket,
    check_action_permission,
    cleanup_stale_agent_artifacts,
    evaluate_due_agents,
    is_git_repo,
    load_agents_config,
    prepare_agent_worktree,
    run_agent,
    run_agent_cycle,
    run_command_bounded,
)

__all__ = [
    "AGENT_ROLES",
    "ALLOWED_AGENT_PROVIDERS",
    "BRANCH_MAX_AGE_DAYS",
    "CADENCE_SECONDS",
    "TIER_AUTO",
    "TIER_AUTO_IF_GREEN",
    "TIER_HUMAN",
    "VALID_CADENCES",
    "AgentConfig",
    "AgentConfigError",
    "AgentRunResult",
    "AgentStateStore",
    "agent_branch_name",
    "agent_status_payload",
    "agents_file_path",
    "bounded_validation_limits",
    "cadence_bucket",
    "check_action_permission",
    "cleanup_stale_agent_artifacts",
    "evaluate_due_agents",
    "is_git_repo",
    "load_agents_config",
    "prepare_agent_worktree",
    "run_agent",
    "run_agent_cycle",
    "run_command_bounded",
]
