float16: Any
bfloat16: Any

class Generator:
    def manual_seed(self, seed: int) -> "Generator": ...
    def to(self, device: str) -> "Generator": ...

def cuda_is_available() -> bool: ...
def cuda_current_device() -> int: ...
def cuda_get_device_properties(index: int) -> Any: ...
def cuda_mem_get_info(index: int) -> tuple[int, int]: ...
