#!/usr/bin/env bash
set -uo pipefail

ALLOW_WRITE="${1:-false}"
TARGET_BRANCH="${2:-main}"
SUMMARY_PATH="${3:-artifacts/agent-hybrid/agent_summary.json}"
REPORT_PATH="${4:-artifacts/agent-hybrid/agent_report.md}"
LOOP_INDEX="${5:-1}"
LOOP_COUNT="${6:-6}"
SESSION_ID="${7:-manual}"
MERGE_POLICY="${8:-safe_gate}"
RETRY_MERGE="${9:-1}"
SAFE_TO_MERGE="${10:-false}"

ACTION="not_attempted"
OK="true"
BRANCH_NAME="agent/swarm-${SESSION_ID}"
PR_NUMBER="0"
PR_URL=""
MERGE_ATTEMPTED="false"
MERGED="false"
MERGE_ATTEMPTS="0"
REBASE_OK="false"
PUSH_OK="false"
MESSAGE=""

emit_markers() {
  printf 'AGENT_PUBLISH_ACTION=%s\n' "${ACTION}"
  printf 'AGENT_PUBLISH_OK=%s\n' "${OK}"
  printf 'AGENT_PUBLISH_BRANCH=%s\n' "${BRANCH_NAME}"
  printf 'AGENT_PUBLISH_PR_NUMBER=%s\n' "${PR_NUMBER}"
  printf 'AGENT_PUBLISH_PR_URL=%s\n' "${PR_URL}"
  printf 'AGENT_PUBLISH_MERGE_ATTEMPTED=%s\n' "${MERGE_ATTEMPTED}"
  printf 'AGENT_PUBLISH_MERGED=%s\n' "${MERGED}"
  printf 'AGENT_PUBLISH_MERGE_ATTEMPTS=%s\n' "${MERGE_ATTEMPTS}"
  printf 'AGENT_PUBLISH_REBASE_OK=%s\n' "${REBASE_OK}"
  printf 'AGENT_PUBLISH_PUSH_OK=%s\n' "${PUSH_OK}"
  printf 'AGENT_PUBLISH_MESSAGE=%s\n' "${MESSAGE}"
}

int_greater_equal() {
  local a b
  a="${1:-0}"
  b="${2:-0}"
  [[ "${a}" =~ ^[0-9]+$ ]] || a="0"
  [[ "${b}" =~ ^[0-9]+$ ]] || b="0"
  [[ "${a}" -ge "${b}" ]]
}

create_pr_body() {
  local body_file
  body_file="${1}"
  {
    echo "## Change Summary"
    echo "- Automated multi-loop swarm output generated by Agent Hybrid workflow."
    echo "- Loop ${LOOP_INDEX}/${LOOP_COUNT} for session ${SESSION_ID}."
    echo ""
    echo "## Why it changed"
    echo "- Keep cloud/deep automation moving with transparent artifacts and controlled autonomous merge behavior."
    echo ""
    echo "## Test evidence"
    echo "- Summary artifact: \\`${SUMMARY_PATH}\\`"
    echo "- Report artifact: \\`${REPORT_PATH}\\`"
    echo ""
    echo "## Risk register"
    echo "- Merge policy: ${MERGE_POLICY}"
    echo "- Safe-to-merge gate: ${SAFE_TO_MERGE}"
    echo ""
    echo "## Next collaboration tasks"
    echo "- [P1][core_reliability] Investigate failing surfaces from current loop artifacts."
    echo "- Acceptance criteria: all failing commands include deterministic repro + owner."
    echo ""
    echo "## Artifact paths"
    echo "- ${SUMMARY_PATH}"
    echo "- ${REPORT_PATH}"
    if [[ -f "${REPORT_PATH}" ]]; then
      echo ""
      echo "## Agent report excerpt"
      echo ""
      sed -n '1,120p' "${REPORT_PATH}"
    fi
  } > "${body_file}"
}

if [[ "${ALLOW_WRITE}" != "true" ]]; then
  ACTION="skipped_write_disabled"
  MESSAGE="Write policy disabled; skipping publish and merge."
  emit_markers
  exit 0
fi

TOKEN_VALUE="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
if [[ -z "${TOKEN_VALUE}" ]]; then
  ACTION="skipped_missing_token"
  OK="false"
  MESSAGE="GH_TOKEN/GITHUB_TOKEN missing; cannot publish or merge."
  emit_markers
  exit 0
fi
export GH_TOKEN="${TOKEN_VALUE}"

if ! command -v gh >/dev/null 2>&1; then
  ACTION="skipped_missing_gh"
  OK="false"
  MESSAGE="gh CLI unavailable; cannot publish or merge."
  emit_markers
  exit 0
fi

if ! git config user.name "hybrid-cloud-agent[bot]"; then
  ACTION="git_config_failed"
  OK="false"
  MESSAGE="Failed to configure git user name."
  emit_markers
  exit 0
fi
if ! git config user.email "hybrid-cloud-agent[bot]@users.noreply.github.com"; then
  ACTION="git_config_failed"
  OK="false"
  MESSAGE="Failed to configure git user email."
  emit_markers
  exit 0
fi

if ! git fetch origin "${TARGET_BRANCH}" --prune; then
  ACTION="git_fetch_failed"
  OK="false"
  MESSAGE="Failed to fetch target branch."
  emit_markers
  exit 0
fi

if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
  if ! git checkout "${BRANCH_NAME}"; then
    ACTION="git_checkout_failed"
    OK="false"
    MESSAGE="Failed to checkout rolling branch."
    emit_markers
    exit 0
  fi
else
  if ! git checkout -b "${BRANCH_NAME}"; then
    ACTION="git_checkout_failed"
    OK="false"
    MESSAGE="Failed to create rolling branch."
    emit_markers
    exit 0
  fi
fi

git add -A
if git diff --cached --quiet; then
  ACTION="no_changes"
  MESSAGE="No staged changes in this loop."
else
  if ! git commit -m "chore(agent): swarm loop ${LOOP_INDEX}/${LOOP_COUNT} session ${SESSION_ID}"; then
    ACTION="git_commit_failed"
    OK="false"
    MESSAGE="Commit failed during publish flow."
    emit_markers
    exit 0
  fi
  ACTION="committed"
  MESSAGE="Committed loop changes to rolling branch."
fi

if git rebase "origin/${TARGET_BRANCH}"; then
  REBASE_OK="true"
else
  git rebase --abort >/dev/null 2>&1 || true
  ACTION="rebase_conflict"
  OK="false"
  MESSAGE="Rebase conflict encountered; merge flow stopped without force push."
  emit_markers
  exit 0
fi

if git push -u origin "${BRANCH_NAME}"; then
  PUSH_OK="true"
else
  if git push origin "${BRANCH_NAME}"; then
    PUSH_OK="true"
  else
    ACTION="push_failed"
    OK="false"
    MESSAGE="Push failed; merge flow stopped without force push."
    emit_markers
    exit 0
  fi
fi

PR_NUMBER="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json number --jq '.[0].number' 2>/dev/null || true)"
PR_URL="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json url --jq '.[0].url' 2>/dev/null || true)"
IS_DRAFT="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json isDraft --jq '.[0].isDraft' 2>/dev/null || true)"
AHEAD_COUNT="$(git rev-list --count "origin/${TARGET_BRANCH}..${BRANCH_NAME}" 2>/dev/null || echo 0)"

PR_BODY_FILE="$(mktemp)"
create_pr_body "${PR_BODY_FILE}"

if [[ -z "${PR_NUMBER}" || "${PR_NUMBER}" == "null" ]]; then
  if [[ "${AHEAD_COUNT}" == "0" ]]; then
    ACTION="no_changes"
    MESSAGE="No commits ahead of target branch; skipping PR creation."
  elif gh pr create \
    --draft \
    --base "${TARGET_BRANCH}" \
    --head "${BRANCH_NAME}" \
    --title "chore(agent): swarm session ${SESSION_ID}" \
    --body-file "${PR_BODY_FILE}" >/dev/null; then
    ACTION="pr_created"
    MESSAGE="Created rolling draft PR."
    PR_NUMBER="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json number --jq '.[0].number' 2>/dev/null || true)"
    PR_URL="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json url --jq '.[0].url' 2>/dev/null || true)"
    IS_DRAFT="$(gh pr list --state open --head "${BRANCH_NAME}" --base "${TARGET_BRANCH}" --json isDraft --jq '.[0].isDraft' 2>/dev/null || true)"
  else
    ACTION="pr_create_failed"
    OK="false"
    MESSAGE="Failed to create PR from rolling branch."
    emit_markers
    exit 0
  fi
elif gh pr edit "${PR_NUMBER}" \
  --title "chore(agent): swarm session ${SESSION_ID}" \
  --body-file "${PR_BODY_FILE}" >/dev/null; then
  ACTION="pr_updated"
  MESSAGE="Updated rolling PR body/title."
else
  ACTION="pr_update_failed"
  OK="false"
  MESSAGE="Failed to update existing PR."
  emit_markers
  exit 0
fi

rm -f "${PR_BODY_FILE}"

if int_greater_equal "${LOOP_INDEX}" "${LOOP_COUNT}"; then
  if [[ -z "${PR_NUMBER}" || "${PR_NUMBER}" == "null" ]]; then
    ACTION="no_changes"
    MESSAGE="Final loop reached with no open PR to merge."
    emit_markers
    exit 0
  fi

  if [[ "${MERGE_POLICY}" == "safe_gate" && "${SAFE_TO_MERGE}" != "true" ]]; then
    ACTION="merge_blocked_safe_gate"
    OK="false"
    MESSAGE="Safe gate blocked final-loop merge due to loop failures."
    emit_markers
    exit 0
  fi

  if [[ "${IS_DRAFT}" == "true" ]]; then
    gh pr ready "${PR_NUMBER}" >/dev/null 2>&1 || true
  fi

  MERGE_ATTEMPTED="true"
  max_attempts=$((RETRY_MERGE + 1))
  if [[ "${max_attempts}" -lt 1 ]]; then
    max_attempts=1
  fi

  attempt=1
  while [[ "${attempt}" -le "${max_attempts}" ]]; do
    MERGE_ATTEMPTS="${attempt}"
    if gh pr merge "${PR_NUMBER}" --squash --delete-branch >/dev/null 2>&1; then
      MERGED="true"
      ACTION="merged"
      MESSAGE="PR merged autonomously on final loop."
      break
    fi
    attempt=$((attempt + 1))
  done

  if [[ "${MERGED}" != "true" ]]; then
    ACTION="merge_failed"
    OK="false"
    MESSAGE="Autonomous merge failed after configured retries."
  fi
fi

emit_markers
exit 0
