#!/usr/bin/env bash
set -euo pipefail

ALLOW_WRITE="${1:-false}"
TARGET_BRANCH="${2:-main}"
SUMMARY_PATH="${3:-artifacts/agent-hybrid/agent_summary.json}"
REPORT_PATH="${4:-artifacts/agent-hybrid/agent_report.md}"

if [[ "${ALLOW_WRITE}" != "true" ]]; then
  echo "Write policy disabled; skipping draft PR publish."
  exit 0
fi

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "GH_TOKEN is missing; skipping draft PR publish."
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is unavailable; skipping draft PR publish."
  exit 0
fi

if [[ -z "$(git status --porcelain)" ]]; then
  echo "No local changes detected; skipping draft PR publish."
  exit 0
fi

git config user.name "hybrid-cloud-agent[bot]"
git config user.email "hybrid-cloud-agent[bot]@users.noreply.github.com"

BRANCH_NAME="agent/hybrid-${GITHUB_RUN_ID:-manual}-$(date +%s)"
git checkout -b "${BRANCH_NAME}"
git add -A
if git diff --cached --quiet; then
  echo "No staged changes to commit; skipping draft PR publish."
  exit 0
fi
git commit -m "chore(agent): automated hybrid deep cycle updates"
git push origin "${BRANCH_NAME}"

PR_BODY_FILE="$(mktemp)"
{
  echo "## Change Summary"
  echo "- Automated deep-cycle output generated by Agent Hybrid workflow."
  echo "- Route: cloud when available, with fallback local/mock path."
  echo ""
  echo "## Test Evidence"
  echo "- Summary artifact: \`${SUMMARY_PATH}\`"
  echo "- Report artifact: \`${REPORT_PATH}\`"
  echo ""
  echo "## Risk Register"
  echo "- Automated output requires maintainer verification before merge."
  echo "- Draft PR policy enforced: no direct merge to main."
  echo ""
  echo "## Next Collaboration Tasks"
  echo "- Review findings and create scoped follow-up issues."
  echo "- Assign owners and acceptance criteria for P1 tasks."
  echo ""
  if [[ -f "${REPORT_PATH}" ]]; then
    echo "## Agent Report Excerpt"
    echo ""
    sed -n '1,120p' "${REPORT_PATH}"
  fi
} > "${PR_BODY_FILE}"

gh pr create \
  --draft \
  --base "${TARGET_BRANCH}" \
  --head "${BRANCH_NAME}" \
  --title "chore(agent): hybrid deep cycle ${GITHUB_RUN_ID:-manual}" \
  --body-file "${PR_BODY_FILE}"

echo "Draft PR created from ${BRANCH_NAME} -> ${TARGET_BRANCH}."
