#!/usr/bin/env bash
# install_daily_report_timer.sh — install + enable the daily security report
# systemd user timer (06:30 daily) with WhatsApp fallback delivery.
#
# The report is generated by scripts/daily_security_report.py. Email goes
# through the Proton Bridge SMTP relay; when email fails (e.g. bridge has no
# account loaded) the report falls back to WhatsApp via the OpenClaw CLI.
#
# WhatsApp delivery config: ~/.config/substrate/security_report.json
#   {"whatsapp": {"enabled": true, "target": "+1XXXXXXXXXX"}}
#
# Rollback: systemctl --user stop daily-security-report.timer
#           systemctl --user disable daily-security-report.timer
set -euo pipefail

UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$UNIT_DIR"

cat > "$UNIT_DIR/daily-security-report.service" <<'EOF'
[Unit]
Description=Daily security report generation
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 /home/ahron/codespace/scripts/daily_security_report.py
Environment=SUBSTRATE_ROOT=/home/ahron/codespace
EOF

cat > "$UNIT_DIR/daily-security-report.timer" <<'EOF'
[Unit]
Description=Daily security report timer

[Timer]
OnCalendar=*-*-* 06:30:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now daily-security-report.timer
echo "daily-security-report.timer enabled:"
systemctl --user list-timers daily-security-report.timer --no-pager
