"""Render engine package: shared contract plus local/hosted engine implementations."""

from __future__ import annotations

from .base import (
    CAPABILITIES,
    KINDS,
    MEMORY_STRATEGIES,
    QUALITY_TIERS,
    SPEED_TIERS,
    EngineSpec,
    RenderEngine,
    RenderFailed,
    RenderRequest,
    RenderResult,
    RenderUnavailable,
    apply_memory_strategy,
    detect_gpu,
    ensure_scratch_env,
    load_engine,
    resize_for_engine,
    scratch_root,
    select_memory_strategy,
    tier_rank,
    write_images,
)
from .hosted import (
    BFLFlux2Engine,
    GeminiImageEngine,
    HostedAPIEngine,
    OpenAIGPTImageEngine,
    OpenRouterImageEngine,
    ReveEngine,
)
from .local_diffusers import (
    Flux1DevGGUFEngine,
    Flux2KleinEngine,
    LocalDiffusersEngine,
    NoobAIXLEngine,
    SDXLEngine,
    ZImageTurboEngine,
)

__all__ = [
    "CAPABILITIES",
    "KINDS",
    "MEMORY_STRATEGIES",
    "QUALITY_TIERS",
    "SPEED_TIERS",
    "BFLFlux2Engine",
    "EngineSpec",
    "Flux1DevGGUFEngine",
    "Flux2KleinEngine",
    "GeminiImageEngine",
    "HostedAPIEngine",
    "LocalDiffusersEngine",
    "NoobAIXLEngine",
    "OpenAIGPTImageEngine",
    "OpenRouterImageEngine",
    "RenderEngine",
    "RenderFailed",
    "RenderRequest",
    "RenderResult",
    "RenderUnavailable",
    "ReveEngine",
    "SDXLEngine",
    "ZImageTurboEngine",
    "apply_memory_strategy",
    "detect_gpu",
    "ensure_scratch_env",
    "load_engine",
    "resize_for_engine",
    "scratch_root",
    "select_memory_strategy",
    "tier_rank",
    "write_images",
]
